# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 15:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            'CREATE EXTENSION pgroonga',
            'DROP EXTENSION pgroonga',
        ),
        migrations.RunSQL(
            'CREATE INDEX idx1 ON testapp_testmodel USING pgroonga (id, text1)',
            'DROP INDEX idx1',
        )
    ]
